version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 app/app.py run -h 0.0.0.0 -p 5000
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:  # or use env_file as you did above
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db     # This is the name of the database service in this file above
      - POSTGRES_PORT=5432
      - POSTGRES_DB=some-postgres
      - ENV_FLASK_APP=app.py
      - ENV_FLASK_RUN_HOST=0.0.0.0
      - ENV_FLASK_RUN_PORT=5000
    depends_on:
      - db

volumes:
  db:
    driver: local
  